#!/usr/bin/perl
#
#             Yong 
# Yet anOther Network monitorinG Installer
#

use strict;
use warnings;
use IO::Socket::INET;
use Net::Ping;

if (($ENV{'USER'}) eq 'root') {
    print "installing yong script in /usr/bin/yong\n";
    system "cp yong /usr/bin/";
    print "installing yong.conf /etc/yong.conf\n"; 
    system "cp yong.conf /etc/";
} else {
    print "you are not root , please run as root\n";
}


print "Install Completed . take a look at /etc/yong.conf and README file \n";
