#!/usr/bin/perl

use strict;
use warnings;
use IO::Socket::INET;
use Sys::Hostname;


my $command;
my $config_file='/etc/yong.conf';
my $next_is_config_file;
my $debug=0;

my $interval; #server checking interval
my $http_page_size_check; #check result page size for huge changes

my @general_buffer;



die "failed to load config file $config_file : $!\n" unless (-r $config_file);


foreach $command (@ARGV) {

    if ($next_is_config_file) {
	if (-r "$command") {
	    &debug ("config file is now $command\n");
	    $config_file=$command;
	    } else {
		die "failed to load config file $command : $!\n";
	    }
$next_is_config_file=0;
next;}


if ($command =~ '-*help') {
    print "Yet anOther Network monitorinG\n";
    print "-c to specify another config file\n";
    print "-D to run in debug mode\n";
    print "-help to see this message\n";
    print "\n";
print "Yong is a tool monitoring services over servers .\n";
print "For additional information, see http:\/\/yong.berlios.de\/\n";
    exit;
} elsif ($command =~ '-*D') {
$debug=1;
next;
} elsif ($command =~ '-*c') {
$next_is_config_file=1;
next;
}

}
    undef $next_is_config_file;


open CONFIG,"$config_file";

my @config_buffer=<CONFIG>;

foreach my $line (@config_buffer) {
    next if ($line =~ /^\#/ );

    if ($line =~ /interval=/) {
	$line=~ s/interval=//;
	$interval=$line;
	&debug ("interval is $line");
    }

    if ($line =~ /http_page_size_check=/) {
	$line=~ s/http_page_size_check=//;
	$http_page_size_check=$line;
	&debug ("http_page_size_check is $line");
    }









}










sub debug {
    if ($debug) {
	print "DEBUG : $_[0]";
    }}
